"""empty message

Revision ID: c3c741469341
Revises: f93dca1fa5d3
Create Date: 2026-03-13 10:17:28.894288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c741469341'
down_revision: Union[str, Sequence[str], None] = 'f93dca1fa5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_ip')
    # ### end Alembic commands ###
