"""empty message

Revision ID: df5f2a2426ba
Revises: c3c741469341
Create Date: 2026-03-13 11:04:26.181887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5f2a2426ba'
down_revision: Union[str, Sequence[str], None] = 'c3c741469341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomalies', sa.Column('severity', sa.String(length=20), nullable=False))
    op.add_column('anomalies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('anomalies', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.alter_column('anomalies', 'log_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('anomalies', 'risk_score')
    op.drop_column('anomalies', 'explanation')
    op.drop_column('anomalies', 'mitre_technique')
    op.drop_column('anomalies', 'anomaly_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomalies', sa.Column('anomaly_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('anomalies', sa.Column('mitre_technique', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('anomalies', sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('anomalies', sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('anomalies', 'log_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('anomalies', 'ip_address')
    op.drop_column('anomalies', 'description')
    op.drop_column('anomalies', 'severity')
    # ### end Alembic commands ###
